---
on:
  push:
    branches:
      - "*"

jobs:
  "build":
    strategy:
      matrix:
        os:
          # - "ubuntu-latest"
          - "macos-latest"
          # - "windows-latest"

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: "true"

      # - uses: "egor-tensin/build-boost@v1"
      #   with:
      #     version: "1.80.0"
      #     libraries: "log system"
      #     directory: "${{ github.workspace }}/lib/boost"

      - name: "Build"
        shell: "bash"
        run: "./build_linux.sh"
