---
on:
  push:
    branches:
      - "*"

jobs:
  "build":
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "macos-12"
          - "windows-latest"

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3"

      - name: "Set up environment"
        shell: "bash"
        run: "./setup_${{ runner.os }}.sh"

      - uses: "egor-tensin/build-boost@v1"
        with:
          configuration: "Debug"
          directory: "${{ github.workspace }}/lib/boost"
          version: "1.80.0"
          libraries: "log system"

      - name: "Build"
        shell: "bash"
        run: "./build_linux.sh"
