---
on:
  push:
    branches:
      - "*"

jobs:
  "build-ubuntu":
    runs-on: "ubuntu-latest"
    steps:
      # - name: "Prepare runner"
      #   shell: "bash"
      #   run: |
      #     set -x
      #     sudo apt-get update -qqqq
      #     sudo apt-get install -qqqq libboost-log-dev libgtk-3-dev

      - uses: "actions/checkout@v3"
        with:
          submodules: "true"

      - uses: "actions/cache@v3"
        with:
          path: "${{ github.workspace }}/lib/boost/boost_*.tar.gz"
          key: "boost-1.80.0"

      - uses: "egor-tensin/build-boost@v1"
        with:
          version: "1.80.0"
          libraries: "log system"
          directory: "{{ github.workspace }}/lib/boost"

      - name: "Build"
        shell: "bash"
        run: "./build_linux.sh"

      - name: "Run"
        run: "./tmp/cmake/src/foobar"



  "build-macos":
    runs-on: "macos-latest"
    steps:
      # - name: "Prepare runner"
      #   shell: "bash"
      #   run: |
      #     set -x
      #     HOMEBREW_NO_AUTO_UPDATE=1 brew install boost

      - uses: "actions/checkout@v3"
        with:
          submodules: "true"

      - uses: "actions/cache@v3"
        with:
          path: "${{ github.workspace }}/lib/boost/boost_*.tar.gz"
          key: "boost-1.80.0"

      - uses: "egor-tensin/build-boost@v1"
        with:
          version: "1.80.0"
          libraries: "log system"
          directory: "{{ github.workspace }}/lib/boost"

      - name: "Build"
        shell: "bash"
        run: "./build_linux.sh"

      - name: "Run"
        run: "./tmp/cmake/src/foobar"



  "build-windows":
    runs-on: "windows-latest"
    steps:
      # - name: "Prepare runner"
      #   shell: "bash"
      #   run: |
      #     choco install boost-msvc-14.1

      - uses: "actions/checkout@v3"
        with:
          submodules: "true"

      - uses: "actions/cache@v3"
        with:
          path: "${{ github.workspace }}/lib/boost/boost_*.tar.gz"
          key: "boost-1.80.0"

      - uses: "egor-tensin/build-boost@v1"
        with:
          version: "1.80.0"
          libraries: "log system"
          directory: "{{ github.workspace }}/lib/boost"

      - name: "Build"
        shell: "bash"
        run: "./build_linux.sh"

      - name: "Run"
        run: "./tmp/cmake/src/foobar"
