---
on:
  push:
    branches:
      - "*"

jobs:
  "build-ubuntu":
    runs-on: "ubuntu-latest"
    steps:
      # - name: "Prepare runner"
      #   shell: "bash"
      #   run: |
      #     set -x
      #     sudo apt-get update -qqqq
      #     sudo apt-get install -qqqq libboost-log-dev libgtk-3-dev

      - uses: "actions/checkout@v3"
        with:
          submodules: "true"

      - uses: "MarkusJx/install-boost@v2.4.0"
        with:
          boost_version: "1.79.0"
          platform_version: "20.04"
          toolset: "gcc"
          link: "static+shared"
          arch: "aarch64"
          boost_install_dir: "./lib"

      - name: "Build"
        shell: "bash"
        run: "./build_linux.sh"

      - name: "Run"
        run: "./tmp/cmake/src/foobar"



  "build-macos":
    runs-on: "macos-latest"
    steps:
      # - name: "Prepare runner"
      #   shell: "bash"
      #   run: |
      #     set -x
      #     HOMEBREW_NO_AUTO_UPDATE=1 brew install boost

      - uses: "actions/checkout@v3"
        with:
          submodules: "true"

      - uses: "MarkusJx/install-boost@v2.4.0"
        with:
          boost_version: "1.79.0"
          platform_version: "11"
          toolset: "clang"
          link: "static+shared"
          boost_install_dir: "./lib"

      - name: "Build"
        shell: "bash"
        run: "./build_linux.sh"

      - name: "Run"
        run: "./tmp/cmake/src/foobar"



  "build-windows":
    runs-on: "windows-latest"
    steps:
      # - name: "Prepare runner"
      #   shell: "bash"
      #   run: |
      #     choco install boost-msvc-14.1

      - uses: "actions/checkout@v3"
        with:
          submodules: "true"

      - uses: "MarkusJx/install-boost@v2.4.0"
        with:
          boost_version: "1.79.0"
          platform_version: "2022"
          toolset: "msvc"
          link: "shared"
          boost_install_dir: "./lib"

      - name: "Build"
        shell: "bash"
        run: "./build_linux.sh"

      - name: "Run"
        run: "./tmp/cmake/src/foobar"
